@startuml

' описание синтаксиса
' https://github.com/plantuml-stdlib/C4-PlantUML
' библиотеки C4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' линии без скруглений
'skinparam Linetype ortho

title
 <b>Передача бесплатных образцов продукции</b>
end title 

' компоненты
Container_Boundary(Web_Приложение, "Web приложение") {
    Component(СозданиеЗаявки, "Создание заявки")
    Component(ПередачаЗаявкиВШину, "Передача заявки в брокер сообщений")
    Component(ИзменениеСтатусаЗаявки, "Изменение статуса заявки")
    Component(ОтправкиПочты, "Отправки почты")
}

Container_Boundary(Шина_Данных, "Брокер сообщений") {
    Component(ПередачаЗаявки, "Передача заявки")
    Component(ПередачаСтатусаЗаявки, "Передача статуса заявки")
}

Container_Boundary(1c_Приложение, "1c") {
    Component(СозданиеЗаказа, "Создание заказа")
    Component(СогласованиеЗаказа, "Согласование заказа")
    Component(ПередачаСтатусаЗаказаВШину, "Передача статуса заявки в брокер сообщений")
    Component(СозданиеПередачи, "Создание передачи обоазцов")
}

System_Ext(Email, "E-Mail System")

' Cвязи
Rel(СозданиеЗаявки, ПередачаЗаявкиВШину, "")
Rel(ПередачаЗаявкиВШину, ПередачаЗаявки, "")
Rel(ПередачаЗаявки, СозданиеЗаказа, "")
Rel(СозданиеЗаказа, СогласованиеЗаказа, "")
Rel(СогласованиеЗаказа, ПередачаСтатусаЗаказаВШину, "")
Rel(СогласованиеЗаказа, СозданиеПередачи, "")
Rel(ПередачаСтатусаЗаказаВШину, ПередачаСтатусаЗаявки, "")
Rel(ПередачаСтатусаЗаявки, ИзменениеСтатусаЗаявки, "")
Rel(ИзменениеСтатусаЗаявки, ОтправкиПочты, "")
Rel_R(ОтправкиПочты, Email, "")

' Расположение
Lay_D(Шина_Данных, 1c_Приложение)
Lay_R(Шина_Данных, 1c_Приложение)
Lay_D(ОтправкиПочты, ИзменениеСтатусаЗаявки)

@enduml